### PR TITLE
E-Stop Remote PCB

### PR DESCRIPTION
**Pull request by noahzemlin**
This PCB integrates the Feather M0 with both the remote control and the hard e-stop. The receiving feather outputs high to SIG_KILL when the button is pressed on the remote. The sending feather sends low to SIG_STOP when the button is pressed which interrupts the feather to send the signal to the receiver. Additionally, the remote has support for a Nokia 5110 display.

Additionally, the PCB is intentionally designed to have the screen and button on one side with the rest on the other. This will allow the installed PCB to be put into the top of the remote, screen side up.

Schematic: https://github.com/SoonerRobotics/igvc_hardware_2020/blob/feat/safety-receiver/Estop%20Remote/Plots/Schematic.pdf

PCB: https://github.com/SoonerRobotics/igvc_hardware_2020/blob/feat/safety-receiver/Estop%20Remote/Plots/PCB.pdf

Related Code: https://github.com/SoonerRobotics/igvc_software_2020/tree/master/firmware/safety

### CODE REVIEW

**Comment by TylerJulian** [comment]
Make sure to include a pdf version of the schematic, so we can read the schematic in browser.

**Comment by noahzemlin** [comment]
Just realized I forgot to connect the LED pin of the 5110, will do that later :)

**Comment by jkleiber** [comment]
Instead of routing ground everywhere, you should use a ground plane by using the pour feature

**Review by j-exinia — APPROVED** [review]
Yeah its a PCB got some traces and a GND fill. You got some comments on the schematic. Looks good mate.

**Review by TylerJulian — APPROVED** [review]
Apperv

**Pull request merged**
