### PR TITLE
Uploaded Revision 1 of Motor Nucleo schematic, WIP

### PR DESCRIPTION
**Pull request by TylerJulian**
First schematic for our Nucleo that controls the motors and reads the encoders. The encoders run at 5v logic so the signal is shifted down to 3.3v logic using a level shifter. Each side of the robot has two motors connected together to provide more torque. The motors share a pwm signal and enable pins on their respective sides. 

The nucleo has the same pinout as an arduino Nano

image

### CODE REVIEW

**Comment by lwbantoto** [comment]
This is too blurry. Please attach a color PDF of the schematic here

**Comment by lwbantoto** [comment]
Which Nucleo are you using? You don't need a level shifter if the pins are 5V tolerant. How are you powering the encoders? What is VCC? Rename VCC to +3V3.  Update your comment such that it includes a color PDF of the schematic. The image you have in your post is too blurry. @TylerJulian

**Comment by jkleiber** [comment]
1. Why are the left enable and right enable wires crossing over? This is entirely avoidable and would make the schematic cleaner
2. Consider using the GND reference rather than passing GND as a wire all over the board. Similarly, use a 3v3 reference like Lance suggested to de-clutter the schematic
3. If you follow 2, then you can move your power and ground pins away and reduce wire crossover

@lwbantoto I'm not sure the pins for the LM432KC are 5V tolerant, but that's something @TylerJulian can look into

**Comment by TylerJulian** [comment]
Per the Nucleo-l432kc datassheet https://www.st.com/resource/en/datasheet/stm32l432kc.pdf, The pins that the encoders use are 5v tolerant, so we do not need a level shifter.

**Comment by TylerJulian** [comment]
The schematic was updated to remove the level shifter and decluttered schematic.

**Comment by TylerJulian** [comment]
[MotorNucleoRev2.pdf](https://github.com/SoonerRobotics/igvc_hardware_2020/files/4252035/MotorNucleoRev2.pdf)

**Comment by lwbantoto** [comment]
This looks much better Tyler. Going to a basketball game so will give more feedback later, when is this board supposed to be sent out by? Are you familiar with net names in KiCad? Take a look at how VCC and GND is on this schematic. You see you don't have to connect it to the connector. Just use a net name! 

image

image

I'm not sure why there are two GND labels for each ground and 5V. Fix that. Capitalize EN and PWM everywhere. Why are some connector labels bolded and some not? Make all text readable from left to right, your connector labels are in the wrong orientation.

**Comment by lwbantoto** [comment]
You don't have to wire stuff from the MCU to the connectors! 
image 

Add net labels to each pin you're using, and add a net label for its corresponding pin on the connector. It will look much cleaner

**Comment by TylerJulian** [comment]
[MotorNucleoRev2.pdf](https://github.com/SoonerRobotics/igvc_hardware_2020/files/4253019/MotorNucleoRev2.pdf)

**Comment by jkleiber** [comment]
Question: The symbol you are using says Arduino Nano 3.x - aren't we using a Nucleo? If so, the symbol should match.

Also, I'd really like it if in the schematic everything was centered. Also, it would be nice if the comments are next to the thing they are describing instead of way off at the top far away from everything. You can make your comments more than one line long by hitting enter instead of letting it wrap in the editor

**Review by noahzemlin — APPROVED** [review]
good enough to order :)

**Pull request merged**
